[package]
name = "switch-quarters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webweg = { path = "../.." }
tokio = { version = "1.17.0", features = ["macros"] }
