name: Rust

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Compilation/Style/Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Documentation Example Compiles
      run: cargo test --doc --verbose
    - name: Run Utility Tests
      run: cargo test --test wrapper_tests -- util_tests
    - name: Clippy
      run: cargo clippy
    - name: Format
      run: cargo fmt --check